blank_issues_enabled: false
contact_links:
  - name: Questions and ideas
    url: https://github.com/alisolphp/LearnHub/discussions
    about: "For open-ended questions, feedback, and ideas, please use GitHub Discussions instead of issues."
